### ISSUE TITLE
Как это чекер работает а?

### ISSUE THREAD

**Issue by Asolka1** [Underneach/Tanki-Online-Checker#1]
Нашел на просторах , не пойму как он работает. В текстовике указаном в пути, написаны акки по типу ( aboba228@gmail.com:password11 ) , как я только не пытался записать акки в этот текстовик, но всегда ошибка при запуске main , В случаи записи такой aboba228@gmail.com:password11 , почта:пароль, выдаёт просто - Process finished with exit code 0 .
В случаи записи просто одной почты ,  то выдаёт - [aboba228@gmail.com] - [ERROR] - [INDEX ERROR] .
Прошу помогите, обьясните в каком виде должна быть база акков. 
И еще один момент, на форум tanki online вход не с почты, а только с игрового НИКА, а если в текстовик который указывается при запуске софта впусывать ник:пароль, то выдаёт просто Process finished with exit code 0. 
ПАМАГИТЕ

**Comment by Underneach** [comment]
https://github.com/Underneach/Tanki-Online-Checker/commit/c56aa1a28d50001bd4b6166be976c193d2176fee
